opendata-swiss/ckanext-switzerland-ng

ckanext/switzerland/logic.py
Apparently this check is not needed. It was also causing an error because, unless you are a sysadmin, the check-access method requires the dataset id. We don't have an id or name for the dataset at this point (it's created a couple of lines down).
=> Don't check for access before updating package from xml.

ckanext/switzerland/templates/package/snippets/additional_info.html
The additional-info section is inside a container (which sets the width for the whole page content), so it should not also be a container itself.
=> Fix html for dataset page.

ckanext/switzerland/helpers/frontend_helpers.py, ckanext/switzerland/templates/group/read_base.html, ckanext/switzerland/templates/header.html, ckanext/switzerland/templates/organization/read_base.html, ckanext/switzerland/templates/package/read_base.html, ckanext/switzerland/templates/scheming/display_snippets/fluent_tags.html, ckanext/switzerland/templates/scheming/package/resource_read.html, ckanext/switzerland/templates/scheming/package/snippets/additional_info.html, ckanext/switzerland/templates/snippets/search_form.html, ckanext/switzerland/templates/user/dashboard.html, ckanext/switzerland/templates/user/read_base.html
- Fix tag links on dataset page going to `/dataset?tags=foo` instead of language-specific `/dataset?keyword_de=foo`.
- Display terms of use on resource and dataset pages.
- Fix the `Reset search` link on the harvester search box.
- Remove `Activity stream` tabs on user, dataset, group and organization pages.
=> Fix a handful of display issues

ckanext/switzerland/logic.py
This means we can try out using the s3 uploader locally with temp credentials, but keep using the local one by default.
=> Don't send xml files to s3

ckanext/switzerland/helpers/request_utils.py
This means we will not transform data that's retrieved from the database by these calls the way we would transform data requested by external API calls.
=> Don't treat requests from JS modules as API requests.

ckanext/switzerland/helpers/plugin_utils.py, ckanext/switzerland/plugins.py
This led to outputting HTML in resource and package descriptions everywhere, including in ttl and xml export. The frontend can render the markdown OK so let's stick with that on our side.
=> Don't render markdown in descriptions

ckanext/switzerland/templates/scheming/package/resource_read.html
I just display the coverage attribute as it is: it can be a date or something else: it has not the usual dateformat, but I decided against transforming it in any way: just displaying it the the way we get it, which is in the format YYYY-MM-DD so far.
=> add attribute coverage on resource detail page

ckanext/switzerland/plugins.py
The above PR will fix the issue for the showcase internal server error which is due to the empty `tracking_summary` field and similar issue was there (https://github.com/ckan/ckan/issues/1343) but not exact same.
=> Add the ignore_missing for the tracking

ckanext/switzerland/dcat-ap-switzerland_scheming.json, ckanext/switzerland/helpers/validators.py, ckanext/switzerland/i18n/ckanext-switzerland.pot, ckanext/switzerland/i18n/de/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/i18n/fr/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/i18n/it/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/plugins.py, ckanext/switzerland/presets.json, ckanext/switzerland/templates/package/read.html, ckanext/switzerland/tests/test_controller.py
Also, translate dataset description using the scheming helper, so that it's more robust in case the description is returned as a dict instead of a string.
=> Validate format of dates matches DD.MM.YYYY

README.md, ckanext/switzerland/i18n/de/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/i18n/fr/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/i18n/it/LC_MESSAGES/ckanext-switzerland.po
These translations were automatically added to the .po files with the update_catalog command in setup.py. Most of them are translations that already exist in ckan or in various ckanexts, and overwriting them with empty strings in our .po files removes the existing translations, so only English is shown. Some of them have translated strings that are the same as the ones in ckan, and it's not necessary to include those in our ckanext as well.
=> Remove erroneously-added translations

ckanext/switzerland/plugins.py
It seems that an outdated call to ogdch_add_users_to_groups was leftover in this function.
=> Fix server error when saving group

ckanext/switzerland/i18n/de/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/i18n/fr/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/i18n/it/LC_MESSAGES/ckanext-switzerland.po
I left off some translations that are very unlikely to ever be seen by users, e.g. those that show if there are no groups at all, or those that we have overwritten with ckanext-scheming.
=> Translate 'group' to 'category' everywhere a user can see

ckanext/switzerland/helpers/dataset_form_helpers.py, ckanext/switzerland/helpers/frontend_helpers.py, ckanext/switzerland/helpers/plugin_utils.py, ckanext/switzerland/helpers/validators.py, ckanext/switzerland/plugins.py, ckanext/switzerland/presets.json, requirements.txt
We have plenty of datasets that might include the date 01.01.1970, which is 0 as a posix timestamp. It should be converted to a date string, not set to None.
=> Fix two issues with datetimes

ckanext/switzerland/helpers/validators.py
Here, we try to parse the date as a string formatted 'DD.MM.YYYY', so we can convert it into POSIX timestamp format. If we get a ParserError it was probably already in POSIX format and we return it as given. If it's a POSIX timestamp that is very large, however (e.g. -3342470400, which is Jan 31 1864), the error given is an OverflowError, so we need to catch that as well.
=> Catch OverflowError when parsing POSIX date with dateutil

ckanext/switzerland/helpers/plugin_utils.py
consider cases where temporals and resources are missing
that is especially the case for dataset_types showcase and harvest
=> repair bug in date transformation

bin/travis-build.bash
checkout of a specific commit of ckanext-dcat is no longer necessary
after ckanext-dcatapchharvest has been adapted to the change
=> repair travis build

ckanext/switzerland/helpers/frontend_helpers.py, ckanext/switzerland/i18n/ckanext-switzerland.pot, ckanext/switzerland/i18n/de/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/i18n/fr/LC_MESSAGES/ckanext-switzerland.po, ckanext/switzerland/i18n/it/LC_MESSAGES/ckanext-switzerland.po
Store EU frequency uris and values (http://publications.europa.eu/resource/authority/frequency)
instead of URLS of the DCAT vocabulary:  http://purl.org/cld/freq
=> Make frequency DCAT-AP compatible

solr/schema.xml
they are added as not mulitivalued, as stored since they might be returned in a search result and as indexed, since we want to search by them
=> feat: add issued and modified to solr schema as fields of type date

ckanext/switzerland/helpers/date_helpers.py, ckanext/switzerland/helpers/plugin_utils.py
issued and modified of the dataset are already set by ckan
res_latest_issued and res_latest_modified are set by the latest of these dates over all resources of a dataset
the resource dates need first to be transformed into isodates after that the maximum over the resulting string values will be the latest date
=> feat: adapt solr indexing to set date fields

ckanext/switzerland/helpers/request_utils.py, ckanext/switzerland/plugins.py, requirements.txt
It is not allowed to make requests to add showcases ofter than 2 times per 5 minutes.
If so we will get: RateLimitException: too many calls
=> Add limitation on API requests to add showcases

ckanext/switzerland/logic.py, ckanext/switzerland/plugins.py
the frontend submits showcases along with datasets: the showcase should be submitted in one go from the frontend, whereas in the backend the showcase submission takes several steps: first the showcase is created, after that for each submitted package a connection to the package is created
=> feat: add custom api route to submit showcases

ckanext/switzerland/logic.py
that way the frontend does not have to provide this and can just pass on the title that was entered in the showcase form
the logic to derive the title is just very simple for now. But a feature to check for already existing names could be added later if needed. It is just better style to derive the slug for the showcase in the ckan backend, when the showcase is stored then doing this in the frontend.
=> feat: derive showcase name from title with a ckan utility

bin/travis-build.bash, ckanext/switzerland/logic.py, ckanext/switzerland/plugins.py
The frontend sends a request to CKAN, e.g. https://ckan.opendata.swiss/api/3/action/ogdch_subscribe_manage?code=[32-character-code] 
and gets back a, e.g., JSON object with the subscription data for that email address
=> Add API route to get subscription details

ckanext/switzerland/logic.py, ckanext/switzerland/plugins.py
The ckanext-subscribe actions expect the user's email address as well as the auth code, which we don't have when calling these routes from the frontend.
=> feat: Add two API routes for dataset subscriptions

ckanext/switzerland/templates/emails/subscribe_verification.html, ckanext/switzerland/templates/emails/subscribe_verification_plain_text.txt, ckanext/switzerland/templates/subscribe/manage.html, ckanext/switzerland/tests/test_subscription_emails.py
This link does not contain an auth code, because the user has not yet verified their subscription and doesn't have one yet. In ckan, the link redirects to a page where the user can request a code be sent to them. On our frontend, we don't have such a page, so the link is useless.
=> feat: Remove manage link from verification email

ckanext/switzerland/helpers/date_helpers.py, ckanext/switzerland/helpers/plugin_utils.py, ckanext/switzerland/tests/test_date_helpers.py
since Solr can only handle dates as isodates with UTC all dates that are indexed by Solr are transformed in the following way: 
for example a date such as `2022-10-25T15:30:10.330000+02:00` that comes in through harvesting is transformed into
`2022-10-25T15:30:10.33Z` ignoring the timezone information
this transformation is only done for Solr, not for the storage in Postgres.
=> feat: transform all datefields that are indexed by Solr

ckanext/switzerland/helpers/mail_helper.py
this is because ckanext-envvars runs after ckan and therefore the config settings that are stored in environment variables are not available at the modules load time
=> fix: env vars are can to be fetched at the load time of the module

ckanext/switzerland/templates/emails/subscribe_notification.html
We don't have an unsubscribe link to fill in when rendering this email, so we use the manage link instead.
=> fix: Link to manage page in notification email, not unsubscribe

ckanext/switzerland/helpers/request_utils.py, ckanext/switzerland/logic.py, ckanext/switzerland/plugins.py
the api rate limit was set before we decided to customize the logic that creates a showcase via an api call. The api limit is moved to guard that new function instead of the previously used way to create showcases
=> fix: rate limit on showcase api calls moved to the api function

ckanext/switzerland/controllers/organization.py
This function is no longer in ckanext-hierarchy, but we still need it.
=> feat: Add function that used to be in ckanext-hierarchy

ckanext/switzerland/dcat-ap-switzerland_scheming.json, ckanext/switzerland/helpers/dataset_form_helpers.py, ckanext/switzerland/plugins.py, ckanext/switzerland/templates/scheming/package/resource_read.html
For making the dct:license  DCAT-AP CH v2 conformant it needs to be mandatory.
=> feat: make license field mandatory, make it a select field and offer the four opendata.swiss licenses as options

ckanext/switzerland/dcat-ap-switzerland_scheming.json, ckanext/switzerland/helpers/dataset_form_helpers.py, ckanext/switzerland/helpers/plugin_utils.py, ckanext/switzerland/helpers/validators.py, ckanext/switzerland/plugins.py, ckanext/switzerland/templates/scheming/form_snippets/multiple_text.html, ckanext/switzerland/templates/scheming/snippets/errors.html, ckanext/switzerland/tests/test_plugin_utils.py, ckanext/switzerland/tests/test_validators.py
- Fix bug where we get a 500 on dataset pages with `None` value for `documentation` field
- Fix bug where adding a single, invalid documentation link adds a link for each letter of that invalid link
- Allow removing documentation links in the CKAN GUI
- Validate that links have a valid url scheme (https or http)
- Override `error.html` template from ckanext-scheming to fix typo, plus display all errors on a field at once (so if you have three invalid links, you can see at once that all three are invalid)
=> fix: Add default values for getting resource docs

ckanext/switzerland/logic.py
If a dataset has a qualified relation that is not on opendata.swiss, it should still be listed on the frontend, so we need to add it to the related_datasets here.
=> fix: Return related datasets that aren't from opendata.swiss

ckanext/switzerland/helpers/localize_utils.py, ckanext/switzerland/helpers/validators.py, ckanext/switzerland/tests/test_helpers_localize.py
E.g. some resources have the name '0' in one language, which gets saved as a string value in a localised dict, but converted to an integer on output. We need to cast that integer value back to a string to display it.
=> fix: Handle multitext strings that get converted to integers

ckanext/switzerland/helpers/date_helpers.py
This includes ISO8601Error, which can be thrown by isodate.parse_datetime.
=> fix: Catch ValueError on parsing datetime

ckanext/switzerland/dcat-ap-switzerland_scheming.json, ckanext/switzerland/helpers/dataset_form_helpers.py, ckanext/switzerland/helpers/frontend_helpers.py, ckanext/switzerland/helpers/plugin_utils.py, ckanext/switzerland/helpers/terms_of_use_utils.py, ckanext/switzerland/helpers/validators.py, ckanext/switzerland/logic.py, ckanext/switzerland/plugins.py, ckanext/switzerland/tests/test_validators.py, solr/schema.xml
1) for the manual corrections of the dataset: show only license 
2) as a "term of use" the licenses should be used to calculate datasets in each license category and display in the  facets
=> Display license instead of rights 

ckanext/switzerland/helpers/dataset_form_helpers.py
we do not need to parse stored publisher JSON, because we have publisher_name as dict or just str., but not str.(of dict)
=> fix: Handling data from stored publisher

ckanext/switzerland/helpers/dataset_form_helpers.py
there are still some publisher stored as:
u'publisher': u'{"url": "https://geoinformation.tg.ch", "name": "Kanton Thurgau, Amt f\\u00fcr Geoinformation"}'
we need to account for them as well
=> Handle publisher that is stored as a str
